c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - vs # [win]
# Please remember to update gcc_compiler_version & clang_compiler_version too.
c_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]
  - 14 # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
c_stdlib:
  - sysroot # [linux]
  - macosx_deployment_target # [osx]
  - vs # [win]
c_stdlib_version: # [unix]
  - 2.28 # [linux]
  - 10.13 # [osx and x86_64]
  - 11.0 # [osx and arm64]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs # [win]
# Please remember to update gxx_compiler_version & clangxx_compiler_version too.
cxx_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]
  - 14 # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
# Rust Compiler Options
rust_compiler:
  - rust
