c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - vs # [win]
c_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs # [win]
cxx_compiler_version: # [unix]
  - 14 # [linux]
  - 19 # [osx]
c_stdlib:
  - sysroot # [linux]
  - macosx_deployment_target # [osx]
  - vs # [win]
c_stdlib_version: # [unix]
  - 2.28 # [linux]
  - 14.0 # [osx and arm64]
rust_compiler:
  - rust
