[project]
channels = ["conda-forge"]
name = "oiio"
platforms = ["win-64"]

[feature.oiio.dependencies]
bzip2 = "==1.0.8"
fmt = "==12.0.0"
freetype = "==2.14.1"
giflib = "==5.2.2"
libheif = "==1.19.7"
libjpeg-turbo = "==3.1.2"
libjxl = "==0.11.1"
libpng = "==1.6.50"
libraw = "==0.21.4"
libtiff = "==4.7.1"
libwebp = "==1.6.0"
openexr = "==3.4.3"
openjpeg = "==2.5.4"
tbb-devel = "==2022.3.0"
yaml-cpp = "==0.8.0"
zlib = "==1.3.1"

[environments]
oiio = ["oiio"]
